apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: arch-k-s
build:
  local:
    concurrency: 1
  artifacts:
    - image: docker.io/reion78/arch-iam
      context: ./
      docker:
        dockerfile: ./dockerfile/arch-iam/Dockerfile
    - image: docker.io/reion78/arch-users
      context: ./
      docker:
        dockerfile: ./dockerfile/arch-users/Dockerfile
    - image: docker.io/reion78/arch-app
      context: ./
      docker:
        dockerfile: ./dockerfile/arch-app/Dockerfile

manifests:
  rawYaml:
    - k8s/*.yml
    - istio/*.yml