apiVersion: v1
kind: ConfigMap
metadata:
  name: arch-app-common-env-configmap
  namespace: arch-namespace
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "arch-iam, arch-users, arch-app"
data:
  spring.output.ansi.enabled: "always"
  ARCH_VERSION: "1.0_istio"
  PROFILES: "kubernetes"
#  JAVA_OPTS: "-Duser.timezone=GMT+08 -Dfile.encoding=UTF-8 -javaagent:/opentelemetry-javaagent.jar"
  JAVA_OPTS: "-Duser.timezone=GMT+08 -Dfile.encoding=UTF-8"
  ARCH_USERS_ADDR: "http://arch-users:8081"
  ISSUE_ADDR: "http://arch-gateway-istio:9000/arch-iam"
#  OTEL_EXPORTER_OTLP_ENDPOINT: "http://arch-otel-col:4318"
#  OTEL_LOGS_EXPORTER: "otlp"
#  OTEL_CONFIG_FILE: ""
#  management.otlp.metrics.export.enabled: "true"
#  management.tracing.enabled: "true"
